apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    project: simpleweb
    env: {{ .Values.env }}
spec:
  selector:
    project: simpleweb
    env: {{ .Values.env }}
  ports:
    - name: listener
      protocol: TCP
      port: 80
      targetPort: 5000